### ISSUE TITLE
Metacontroller Roadmap (2018)

### ISSUE THREAD

**Issue by enisoc** [GoogleCloudPlatform/kube-metacontroller#9]
This is a tentative outline of future plans for Metacontroller.

See the [project board](https://github.com/GoogleCloudPlatform/kube-metacontroller/projects/1) for the status of individual tasks. The backlog there is split into three columns:

* Proposed: Not fleshed out enough to implement yet. Needs discussion.
* Blocked: We know what to do, but it has to wait for something external to happen.
* Ready: We're ready to do this, but no one has picked it up yet.

### Q1 2018

- [ ] Add example to demonstrate building an [Operator](https://coreos.com/operators/) with Metacontroller.
  - [ ] [Vitess](http://vitess.io) Operator example.
- [ ] [Alpha release](https://github.com/GoogleCloudPlatform/kube-metacontroller/milestone/1).
  - [ ] Publish design doc.
  - [ ] Remove warning about running in real clusters (use watches instead of excessive polling).
  - [ ] Document alpha API for k8s objects (e.g. CompositeController) and corresponding webhook objects (Request/Response).
  - [ ] Regression test suite (unit, integration, e2e).
  - [ ] Emit events on controller parent objects and document how to debug controllers when developing with Metacontroller.
  - [ ] Internal refactors (break up `main` package, restructure to support multiple controller patterns).

### Q2 2018

- [ ] Beta release.
  - [ ] API is a candidate for GA, although there could still be breaking changes if necessary.
  - [ ] Scalability benchmarks.
  - [ ] Support mutual authentication of webhook requests.
  - [ ] Support least privilege (e.g. ServiceAccount per controller).
  - [ ] Support more controller patterns (in addition to CompositeController).
  - [ ] Document best practices for developing controllers with Metacontroller.

### Q3 2018

- [ ] 1.0 release.
  - [ ] API will be backward compatible in future 1.x.y releases.
  - [ ] Clean up dependencies (share code instead of copying from k8s/k8s).
  - [ ] Support installing/updating through k8s add-on manager.

### Q4 2018

- [ ] Deprecate Metacontroller in favor of the next new thing.

**Comment by bgrant0607** [comment]
Have you thought about a meta admission controller for validation, defaulting, and policy enforcement?
